uint64 timestamp
string name
uint32 simulation_step
Position pos
uint32 charge
uint32 charge_max
uint32 load
uint32 load_max
uint32 speed
uint32 skill
uint32 vision
string last_action
string last_action_result
Item[] items
Resource[] known_resources
Well[] known_wells
string role
bool in_facility
string facility
#Maybe add inFacility and fPosition if necessary
#More optional information like current route, last action, last action result could be added as well
